export const COMMON = {
    LOADING_CHANGE: 'LOADING_CHANGE',
    LOADING_FINISHED: 'LOADING_FINISHED',
    ROUTE_CHANGE: 'ROUTE_CHANGE',
    LOCALE_CHANGE: 'LOCALE_CHANGE',
};

export const HOME = {
    TASKS_LOAD: 'TASKS_LOAD',
    TASKS_SHOW_OFFSET: 'TASKS_SHOW_OFFSET',
    DUE_TASKS_LOAD: 'DUE_TASKS_LOAD',
    DUE_TASKS_SHOW_HOVER: 'DUE_TASKS_SHOW_HOVER',
    TASKS_TASK_DETAIL: 'TASKS_TASK_DETAIL',
};

export const AREA = {
    AREAS_SHOW_ALL: 'AREAS_SHOW_ALL',
    AREAS_SHOW_MINE: 'AREAS_SHOW_MINE',
    AREAS_AREA_DETAIL: 'AREAS_AREA_DETAIL',
    AREAS_CREATE_AREA: 'AREAS_CREATE_AREA',
    AREAS_CREATE_STEP_0: 'AREAS_CREATE_STEP_0',
    AREAS_CREATE_STEP_1: 'AREAS_CREATE_STEP_1',
};

export const PROJECT = {
    PROJECTS_LOAD: 'PROJECTS_LOAD',
    PROJECTS_SHOW_MEMBER: 'PROJECTS_SHOW_MEMBER',
    PROJECTS_SHOW_CREATED: 'PROJECTS_SHOW_CREATED',
    PROJECTS_SHOW_STARRED: 'PROJECTS_SHOW_STARRED',
    PROJECTS_STAR_PROJECT: 'PROJECTS_STAR_PROJECT',
    PROJECTS_LIST_FILTER: 'PROJECTS_LIST_FILTER',
    PROJECTS_CREATE_PROJECT: 'PROJECTS_CREATE_PROJECT',
    PROJECTS_CREATE_STEP_0: 'PROJECTS_CREATE_STEP_0',
    PROJECTS_CREATE_STEP_1: 'PROJECTS_CREATE_STEP_1',
    PROJECTS_PROJECT_DETAIL: 'PROJECTS_PROJECT_DETAIL',
    PROJECTS_PROJECT_DETAIL_ID: 'PROJECTS_PROJECT_DETAIL_ID',
};
